openapi: 3.0.4
components:
  schemas:
    TranslateTextRequest:
      type: object
      properties:
        sourceLanguage:
          type: string
          description: The language code of the source text.
          example: "English"
        targetLanguage:
          type: string
          description: The language code to translate the text into.
          example: "Japanese"
        text:
          type: string
          description: The text to be translated.
          example: "Hello, world!"
      required:
        - sourceLanguage
        - targetLanguage
        - text
